apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-helper
  namespace: webapp
  labels:
    app: ubuntu-helper
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      tty: true
