apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ubuntu-sa-nodes
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ubuntu-sa-nodes-binding
subjects:
  - kind: ServiceAccount
    name: ubuntu-sa
    namespace: webapp
roleRef:
  kind: ClusterRole
  name: ubuntu-sa-nodes
  apiGroup: rbac.authorization.k8s.io

